version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    env_file: .env-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: