version: '3'

services:
  db:
    image: postgres
    # restart: always
    # env_file: .env-db
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    # volumes:
    #   - .:/code
    ports:
      - "8001:8001"
    # env_file: .env
    depends_on:
      - db